nginx:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  volumes:
    # Mount docker socket so that proxy can automatically detect backends
    - /var/run/docker.sock:/tmp/docker.sock:ro
    
    # Mount self signed https certificates for testing
    - ${HOME}/.gdev/certs:/etc/nginx/certs:ro
  restart: always
dnsmasq:
  image: andyshinn/dnsmasq
  ports:
    - "{BOX_IP}:53:53/tcp"
    - "{BOX_IP}:53:53/udp"
    - "172.17.0.1:53:53/tcp"
    - "172.17.0.1:53:53/udp"
  cap_add:
    - NET_ADMIN
  # TODO: can't use {BOX_IP} because the variable won't get interpolated
  command: "--address=/test/$BOX_IP"
  restart: always
  environment:
    BOX_IP: "{BOX_IP}"
mail:
  image: mailhog/mailhog
  environment:
    # Use easier domain name for mailhog
    VIRTUAL_HOST: mail.test
    VIRTUAL_PORT: 8025
  ports:
    # Map mailhog into host machine port
    # This port is used in production too
    - 172.17.0.1:25:1025
  restart: always
generator:
  image: onnimonni/signaler
  environment:
    GENERATOR: "self-signed"
  volumes:
    # Mount .gdev folders to store certificates in
    - ${HOME}/.gdev/certs:/data/certs
    - ${HOME}/.gdev/ca:/data/ca

    # Mount docker socket so that signaler can auto create certificates
    - /var/run/docker.sock:/tmp/docker.sock:ro
  restart: always